services:
  - type: web
    name: fintrack
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: GROQ_API_KEY
        sync: false
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/instance
      sizeGB: 1
